<?php
echo "<pre>";
echo strlen("Hello");
echo "<br>";
echo str_word_count ("Hello");
echo "<br>";
echo strrev("Hello");
echo "<br>";
$name="Mango is a fruit";
echo stripos($name,"o");
echo "<br>";
echo str_replace("Mango","Litchi",$name);
echo "<br>";
echo str_repeat($name,10);
echo "<br>";
echo('"Hello"');
echo "<br>";
echo trim($name);
echo "<br>";
echo rtrim('   Hello   ');
echo "<br>";
echo ltrim('   Hello   ');
echo "<br>";
echo strcmp("Hello","hello");
echo "<br>";
echo strcasecmp("HELLO","Hello");
echo "<br>";
echo strtolower("HeLLo");
echo "<br>";
echo strtoupper("HeLLo");
echo "<br>";
print_r (str_split("Hello"));
echo "<br>";
echo ucwords("hello world");
$fname="Akriti";
echo substr($fname,-2,-3);
$file="csit.py";
echo substr($file,-2);
?>